# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package compclusteringengine;
use base qw(Exporter);
use base qw(DynaLoader);
package compclusteringenginec;
bootstrap compclusteringengine;
package compclusteringengine;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package compclusteringengine;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package compclusteringengine;


############# Class : compclusteringengine::CompClusteringEngine ##############

package compclusteringengine::CompClusteringEngine;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( compclusteringengine );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = compclusteringenginec::new_CompClusteringEngine(@_);
    bless $self, $pkg if defined($self);
}

*getDataImgHeight = *compclusteringenginec::CompClusteringEngine_getDataImgHeight;
*getDataImgWidth = *compclusteringenginec::CompClusteringEngine_getDataImgWidth;
*getErrorString = *compclusteringenginec::CompClusteringEngine_getErrorString;
*paintClusteringData = *compclusteringenginec::CompClusteringEngine_paintClusteringData;
*paintCogs = *compclusteringenginec::CompClusteringEngine_paintCogs;
*paintHorizontalTree = *compclusteringenginec::CompClusteringEngine_paintHorizontalTree;
*paintMetagenomes = *compclusteringenginec::CompClusteringEngine_paintMetagenomes;
*paintScale = *compclusteringenginec::CompClusteringEngine_paintScale;
*paintVerticalTree = *compclusteringenginec::CompClusteringEngine_paintVerticalTree;
*paintZoomImage = *compclusteringenginec::CompClusteringEngine_paintZoomImage;
*readFile = *compclusteringenginec::CompClusteringEngine_readFile;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        compclusteringenginec::delete_CompClusteringEngine($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package compclusteringengine;

1;
